/**
 * Generate a verification worksheet for the transfer-fee table (audit finding M4).
 *
 *   npm run fee-worksheet
 *
 * Writes two files to the repo root, both gitignored:
 *   transfer-fee-worksheet.csv  — one row per exchange×coin×network, for a spreadsheet
 *   transfer-fee-worksheet.md   — per-exchange summary + progress tracker
 *
 * Why this exists: `TRANSFER_FEES_LAST_VERIFIED` is 2025-06-01 and the table holds
 * ~560 entries. Re-verifying it by reading TypeScript is miserable and error-prone —
 * you lose your place, and nothing records what you already checked. The CSV gives
 * you the current value next to blank columns to fill in, so the job is comparing
 * rather than transcribing.
 *
 * The unit of work is ONE EXCHANGE, not one entry: you open an exchange's fee page
 * once and check every row it covers. Rows are sorted tier-1 first, then by
 * exchange, so the highest-traffic tables come first and you can stop at any
 * exchange boundary without leaving a half-checked table behind.
 *
 * IMPORTANT — this script only reads. Nothing here bumps TRANSFER_FEES_LAST_VERIFIED.
 * That date means "the whole table was verified as of this day", so it can only be
 * moved by hand once every exchange is done. Bumping it after a partial pass is the
 * exact dishonesty the provenance machinery exists to prevent.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import {
  EXCHANGES,
  TRANSFER_FEES_LAST_VERIFIED,
  transferFeesAgeDays,
  SPOT_TRADING_FEES,
  TRADING_FEES_COMPILED,
} from '../src/lib/data/transferFees'
// The row list, the impact ranking, the fee-page links and the core-45 cut are shared
// with the owner's check page (gen-fee-check-page.ts), so the two cannot disagree.
import { feeRows, byImpact, FEE_PAGES, CORE_N, type FeeRow } from './lib/transferFeeRows'

// ─── What the machine already did ────────────────────────────────────────────
//
// `npm run fee-reconcile` verifies every row a live exchange API covers. Asking
// a person to re-check those by hand wastes the scarcest resource in this job —
// their patience — so they are excluded here and reported as already done.
const RECONCILE_FILE = join(process.cwd(), 'transfer-fee-reconcile.json')
const reconciledKeys = new Set<string>()
let reconcileDate: string | null = null
if (existsSync(RECONCILE_FILE)) {
  try {
    const r = JSON.parse(readFileSync(RECONCILE_FILE, 'utf8'))
    reconcileDate = r.runDate ?? null
    for (const k of r.confirmedRows ?? []) reconciledKeys.add(k)
    for (const p of r.proposals ?? []) reconciledKeys.add(`${p.exchangeId}:${p.coinId}:${p.networkId}`)
  } catch { /* a malformed artifact just means nothing is excluded */ }
}

const csvCell = (v: unknown): string => {
  const s = v === undefined || v === null ? '' : String(v)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

interface Row extends FeeRow {
  /** Verified by machine against the exchange's own API — no human check needed. */
  reconciled: boolean
}

const rows: Row[] = feeRows(EXCHANGES).map((r) => ({ ...r, reconciled: reconciledKeys.has(r.key) }))

// Outstanding work first, highest-impact first within that — then everything
// else, so the top of the file is the part actually worth someone's afternoon.
// Ties break alphabetically so the file is stable across runs and diffs cleanly.
rows.sort((a, b) => Number(a.reconciled) - Number(b.reconciled) || byImpact(a, b))

const outstanding = rows.filter((r) => !r.reconciled)
const core = outstanding.slice(0, CORE_N)

// ─── CSV ─────────────────────────────────────────────────────────────────────
const header = [
  'Tier', 'Exchange', 'Coin', 'Network',
  'Current fee', 'Current min', 'Withdraw on?', 'Deposit on?',
  'Existing note', 'Checked 2026-07?', 'Machine-verified?', 'Impact',
  // Blank columns for the person doing the work.
  'ACTUAL fee', 'ACTUAL min', 'Status (ok/changed/delisted/unavailable)', 'Date checked', 'Comment',
]

const csv = [
  header.map(csvCell).join(','),
  ...rows.map((r) =>
    [
      r.tier, r.exchange, r.coin, r.network,
      r.fee, r.minWithdraw, r.withdrawEnabled ? 'yes' : 'NO', r.depositEnabled ? 'yes' : 'NO',
      r.note, r.recentlyChecked ? 'yes' : '',
      r.reconciled ? 'yes — skip' : '', r.impact,
      '', '', '', '', '',
    ].map(csvCell).join(',')
  ),
].join('\n')

// ─── Markdown tracker ────────────────────────────────────────────────────────
const byExchange = new Map<string, Row[]>()
for (const r of rows) {
  const list = byExchange.get(r.exchange) ?? []
  list.push(r)
  byExchange.set(r.exchange, list)
}

const age = transferFeesAgeDays(new Date())
const md: string[] = [
  '# Transfer-fee verification worksheet (audit finding M4)',
  '',
  `Generated from \`src/lib/data/transferFees.ts\`. **Do not edit this file** — it is`,
  `regenerated by \`npm run fee-worksheet\`. Record findings in the CSV.`,
  '',
  `- **Entries still needing a human:** ${outstanding.length} of ${rows.length}`,
  reconciledKeys.size
    ? `- **Already machine-verified against exchange APIs${reconcileDate ? ` on ${reconcileDate}` : ''}:** ${rows.length - outstanding.length} — skip these`
    : `- **No reconcile artifact found** — run \`npm run fee-reconcile\` first and regenerate; it removes ~115 rows from this job`,
  `- **Exchanges:** ${byExchange.size}`,
  `- **Table last fully verified:** ${TRANSFER_FEES_LAST_VERIFIED} (**${age} days ago**)`,
  `- **Already checked in the 2026-07-20 partial pass:** ${rows.filter((r) => r.recentlyChecked).length}`,
  '',
  '## Start here: the core ' + CORE_N + '',
  '',
  'These are the highest-impact outstanding rows — high-traffic exchanges crossed',
  'with the coins and networks people actually move. Doing just these covers most',
  'real routes. The ranking is a **judgement about usage, not measured data**; it',
  'affects only the order of work, never a fee value.',
  '',
  '| ✔ | Exchange | Coin | Network | Current fee | Fee page |',
  '|---|----------|------|---------|-------------|----------|',
  ...core.map((r) => `| [ ] | ${r.exchange} | ${r.coin} | ${r.network} | ${r.fee} | ${FEE_PAGES[r.exchangeId] ?? '—'} |`),
  '',
  '## How to use this',
  '',
  '0. Rows marked **machine-verified** were checked against the exchange\'s own API',
  '   by `npm run fee-reconcile` — skip them, they are already done.',
  '1. Work **one exchange at a time** — open its fee page once, check every row it covers.',
  '2. Fill the ACTUAL columns in the CSV. Leave a row blank if you did not check it;',
  '   blank means unknown, which is honest. Do not copy the current value across.',
  '3. Statuses: `ok` (matches), `changed` (fill ACTUAL), `delisted` (pair no longer offered),',
  '   `unavailable` (fee not published without login/API).',
  '4. When **every** exchange is done, bump `TRANSFER_FEES_LAST_VERIFIED` by hand.',
  '   That date asserts the whole table was verified — a partial pass must not move it.',
  '   This is why the 2026-07-20 pass deliberately left it alone.',
  '',
  '## Progress',
  '',
  '| ✔ | Exchange | Tier | Entries | Coins | Fee page (unverified starting point) |',
  '|---|----------|------|---------|-------|--------------------------------------|',
]

for (const [name, list] of [...byExchange.entries()].sort(
  (a, b) => a[1][0].tier - b[1][0].tier || a[0].localeCompare(b[0])
)) {
  const coins = new Set(list.map((r) => r.coin)).size
  const url = FEE_PAGES[list[0].exchangeId] ?? '—'
  md.push(`| [ ] | ${name} | ${list[0].tier} | ${list.length} | ${coins} | ${url} |`)
}

md.push(
  '',
  '## Notes worth knowing before you start',
  '',
  '- **Dynamic fees.** Several entries are marked "Dynamic — adjusts with gas". Those can',
  '  never be exactly right; the job is checking the value is still *representative*, not',
  '  identical. Record the observed range in the Comment column.',
  '- **Login walls.** Some exchanges only show live withdrawal fees to signed-in users.',
  '  Mark those `unavailable` rather than guessing — an unverified row recorded as verified',
  '  is worse than one left blank.',
  '- **Delistings are findings.** A pair that no longer exists should be removed from the',
  '  table, not left with a stale fee. Flag it `delisted` and it can be deleted in the',
  '  follow-up commit.',
  '- **Disabled rows still matter.** `Withdraw on?` = NO entries are load-bearing: the path',
  '  finder uses them to exclude routes. If a network has been re-enabled, that changes',
  '  which routes the calculator offers.',
  ''
)

// ── Spot trading fees (S3) — seeded, needs the same verification pass ─────────
md.push(
  '## Spot trading fees (seeded ' + TRADING_FEES_COMPILED + ' — verify alongside withdrawals)',
  '',
  'Default-tier maker/taker per exchange, powering the "all-in cost of sale" panel.',
  'Seeded from published schedules, confidence pinned LOW until verified. Check the',
  'spot fee schedule page while you have each exchange open for withdrawals.',
  '',
  '| Done | Exchange | Maker % | Taker % | Note | Observed maker | Observed taker |',
  '|------|----------|---------|---------|------|----------------|----------------|',
)
for (const ex of EXCHANGES) {
  const f = SPOT_TRADING_FEES[ex.id]
  md.push(
    `| [ ] | ${ex.name} | ${f ? f.makerPct : 'NOT CATALOGUED'} | ${f ? f.takerPct : '—'} | ${f?.note ?? ''} |  |  |`,
  )
}
md.push('')

const root = join(process.cwd(), '..')
writeFileSync(join(root, 'transfer-fee-worksheet.csv'), csv + '\n', 'utf8')
writeFileSync(join(root, 'transfer-fee-worksheet.md'), md.join('\n'), 'utf8')

console.log(`transfer-fee worksheet written`)
console.log(`  ${outstanding.length} entries still needing a human (of ${rows.length}) across ${byExchange.size} exchanges`)
console.log(`  ${rows.length - outstanding.length} already machine-verified — excluded from the job`)
console.log(`  core list: the top ${Math.min(CORE_N, outstanding.length)} by impact are called out first`)
console.log(`  table last fully verified ${TRANSFER_FEES_LAST_VERIFIED} (${age} days ago)`)
console.log(`  ${rows.filter((r) => r.recentlyChecked).length} already checked in the 2026-07 partial pass`)
console.log(`  → transfer-fee-worksheet.csv (fill this in)`)
console.log(`  → transfer-fee-worksheet.md (progress tracker)`)
